# Generated by Django 3.2 on 2021-04-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matzip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('keyword', models.CharField(max_length=30)),
                ('allowed', models.BooleanField()),
            ],
        ),
    ]
