# Generated by Django 3.2 on 2021-05-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matzip', '0006_matzip_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matzip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
