# Generated by Django 3.2 on 2021-07-14 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matzip', '0007_alter_matzip_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matzip',
            name='image',
        ),
    ]
